version: '3'

services:
    app:
        image: tsserver:latest
        ports:
            - "3000:3000"
        command: npx ts-node index.ts
        environment: 
            - PORT=3000
    nginx:
        image: nginx:latest
        ports:
            - "5000:80"
        command: ["nginx", "-g", "daemon off;","-c","/etc/nginx/nginx.conf"]
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
            - app